### ISSUE TITLE
tohgr issue

### ISSUE THREAD

**Issue by V0lk3n** [esphynox/eXit#2]
Hello there,

I was trying to run your game on my linux system. But unfortunately tohgr cannot run on linux.

**Comment by V0lk3n** [comment]
```
$ ./tohgr              
zsh: exec format error: ./tohgr
```

**Comment by esphynox** [comment]
I borrowed `tohgr` tool from here. There is source code for it. I think you can compile it yourself and just put binary in repo and that should work.

http://wsxyz.net/tohgr.html

**Comment by V0lk3n** [comment]
Thanks :)
